version: '3'

services:
  db:
    image: mysql:5.6
    environment:
      MYSQL_ROOT_PASSWORD: "123456"
  web:
    build: .
    command: python manage.py runserver 0.0.0.0:8001
    volumes:
      - ./app:/app
    ports:
      - "8001:8001"
    depends_on:
      - db
